# ---------- BUILD STAGE ----------
FROM node:18-slim AS builder

WORKDIR /usr/src/app

# Cài dependency
COPY package*.json ./
RUN apt-get update && apt-get install -y openssl \
  && npm ci

# Copy source
COPY . .

# Build Vite App
RUN npm run build

# ---------- RUNTIME STAGE ----------
FROM nginx:alpine

# Copy built assets từ builder stage
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 8080 (phải khớp với nginx.conf)
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
