version: '3.9'

services:
  vite_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: vite_react_app_prod
    working_dir: /usr/src/app
    ports:
      - "${EXTERNAL_PORT:-8082}:8080"
    env_file:
      - .env.prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s