FROM node:20-slim

# Enable pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

# Install curl for healthcheck
RUN apt-get update && apt-get install -y curl

COPY . .

EXPOSE 8080

#CMD ["pnpm", "dev", "--host", "0.0.0.0", "--port", "8080"]
CMD ["pnpm", "preview", "--host", "0.0.0.0", "--port", "8080"]