version: '3.9'

services:
  vite_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vite_react_app_dev
    working_dir: /usr/src/app
    ports:
      - "8081:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.dev
    environment:
      - VITE_BASIC_AUTH_USER=goouty
      - VITE_BASIC_AUTH_PASS=minh_long_hoang
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s